obj-m += gl_hw_wdt.o

# gl_hw_wdt-objs := gl_hw_wdt.o

# RELEASE = $(shell uname -r)
# LINUX = /usr/src/linux-headers-$(RELEASE)

# all:
# 	$(MAKE) -C $(LINUX) M=$(PWD) modules

# clean:
# 	$(MAKE) -C $(LINUX) M=$(PWD) clean

# install:
# 	sudo install -m 644 -c gl_hw_wdt.ko /lib/modules/$(RELEASE)
# 	sudo depmod

